using Buildline.Platform.Shared.Domain.Model.Entities;

namespace Buildline.Platform.Categories.Domain.Model.Aggregates;

/// <summary>
///     Aggregate root that represents a material category used to classify construction supplies.
/// </summary>
/// <remarks>
///     Categories are shared reference data for materials, requisitions and inventory filters. The
///     current Sprint 3 API exposes categories as read-only data because the frontend needs stable
///     classification values before full catalog administration is introduced.
/// </remarks>
public partial class Category : IAuditableEntity
{
    /// <summary>
    ///     Initializes an empty category instance for Entity Framework Core materialization.
    /// </summary>
    /// <remarks>
    ///     Domain code should use the public constructor. EF Core uses this protected constructor when
    ///     rebuilding persisted category aggregates.
    /// </remarks>
    protected Category()
    {
        Name = string.Empty;
        Description = string.Empty;
    }

    /// <summary>
    ///     Creates a material category reference.
    /// </summary>
    /// <param name="name">Short category name displayed by frontend filters.</param>
    /// <param name="description">Business description that explains which materials belong to the category.</param>
    public Category(string name, string description)
    {
        Name = name;
        Description = description;
    }

    /// <summary>
    ///     Gets the persistence identity generated by the database.
    /// </summary>
    public int Id { get; private set; }

    /// <summary>
    ///     Gets the category name used by material catalog and inventory views.
    /// </summary>
    public string Name { get; private set; }

    /// <summary>
    ///     Gets the category description shown in API documentation and administrative views.
    /// </summary>
    public string Description { get; private set; }

    /// <summary>
    ///     Gets or sets the audit timestamp captured when the category is first persisted.
    /// </summary>
    public DateTimeOffset? CreatedAt { get; set; }

    /// <summary>
    ///     Gets or sets the audit timestamp captured when the category is updated.
    /// </summary>
    public DateTimeOffset? UpdatedAt { get; set; }
}
