
namespace Buildline.Platform.Profiles.Domain.Model.Aggregates;

/// <summary>
///     Company profile aggregate root for a Buildline tenant.
/// </summary>
/// <remarks>
///     The current frontend consumes a company profile with company name, RUC,
///     address, phone and email. The aggregate keeps those concepts explicit
///     instead of leaking presentation DTO names into the domain.
/// </remarks>
public partial class Profile
{
    /// <summary>
    ///     Initializes an empty profile instance for Entity Framework Core materialization.
    /// </summary>
    /// <remarks>
    ///     Domain code should use the public constructor so company profile fields are explicit.
    /// </remarks>
    protected Profile()
    {
        CompanyName = string.Empty;
        Ruc = string.Empty;
        Address = string.Empty;
        Phone = string.Empty;
        Email = string.Empty;
    }

    /// <summary>
    ///     Creates a company profile aggregate.
    /// </summary>
    /// <param name="companyName">Legal or commercial company name.</param>
    /// <param name="ruc">Peruvian taxpayer identifier used by the company.</param>
    /// <param name="address">Company address displayed in profile settings.</param>
    /// <param name="phone">Company contact phone.</param>
    /// <param name="email">Company contact email.</param>
    public Profile(string companyName, string ruc, string address, string phone, string email)
    {
        CompanyName = companyName;
        Ruc = ruc;
        Address = address;
        Phone = phone;
        Email = email;
    }

    /// <summary>
    ///     Gets the persistence identity generated by the database.
    /// </summary>
    public int Id { get; private set; }

    /// <summary>
    ///     Gets the company name shown in profile settings.
    /// </summary>
    public string CompanyName { get; private set; }

    /// <summary>
    ///     Gets the company RUC value.
    /// </summary>
    public string Ruc { get; private set; }

    /// <summary>
    ///     Gets the company address.
    /// </summary>
    public string Address { get; private set; }

    /// <summary>
    ///     Gets the company contact phone.
    /// </summary>
    public string Phone { get; private set; }

    /// <summary>
    ///     Gets the company contact email.
    /// </summary>
    public string Email { get; private set; }

    /// <summary>
    ///     Updates company profile contact information.
    /// </summary>
    /// <param name="companyName">Updated company name.</param>
    /// <param name="ruc">Updated company RUC.</param>
    /// <param name="address">Updated company address.</param>
    /// <param name="phone">Updated company phone.</param>
    /// <param name="email">Updated company email.</param>
    public void UpdateCompanyInformation(string companyName, string ruc, string address, string phone, string email)
    {
        CompanyName = companyName;
        Ruc = ruc;
        Address = address;
        Phone = phone;
        Email = email;
    }
}
