using System.Text.Json.Serialization;
using Buildline.Platform.Iam.Domain.Model.Commands;
using Buildline.Platform.Shared.Domain.Model.Entities;

namespace Buildline.Platform.Iam.Domain.Model.Aggregates;

/// <summary>
///     Aggregate root that represents an authenticated Buildline account and the user-management
///     fields consumed by the Sprint 2 frontend contract.
/// </summary>
/// <remarks>
///     The IAM bounded context owns credentials, access status and role assignment. Profile-specific
///     data may later move to the Profiles bounded context through an ACL, but this aggregate keeps
///     the operational fields required by the current users API: name, email, role, department,
///     phone, avatar color, active flag and last login display value.
/// </remarks>
public partial class User : IAuditableEntity
{
    /// <summary>
    ///     Initializes an empty user instance for Entity Framework Core materialization.
    /// </summary>
    /// <remarks>
    ///     Domain code should use the public constructors so mandatory identity fields are provided
    ///     explicitly. EF Core requires this constructor to rebuild persisted aggregates.
    /// </remarks>
    protected User()
    {
        Name = string.Empty;
        Email = string.Empty;
        PasswordHash = string.Empty;
        Role = string.Empty;
        Department = string.Empty;
        Phone = string.Empty;
        AvatarColor = string.Empty;
        LastLogin = string.Empty;
        TwoFactorEnabled = false;
        MembershipStatus = "active";
    }

    /// <summary>
    ///     Creates a user aggregate from validated user-management data.
    /// </summary>
    /// <param name="name">Display name shown in user administration views.</param>
    /// <param name="email">Unique email used as the sign-in identifier.</param>
    /// <param name="passwordHash">BCrypt password hash; plain text passwords must never reach the aggregate.</param>
    /// <param name="role">Application role assigned to the user, such as Administrator or Project Manager.</param>
    /// <param name="department">Business area or department associated with the user.</param>
    /// <param name="phone">Contact phone displayed by the frontend when available.</param>
    /// <param name="avatarColor">UI color token used by the frontend avatar fallback.</param>
    /// <param name="isActive">Flag that controls whether the account can authenticate.</param>
    /// <param name="lastLogin">Human-readable last-login value expected by the current frontend contract.</param>
    /// <param name="twoFactorEnabled">Two-factor authentication preference stored for the Settings screen.</param>
    /// <param name="companyId">Identifier of the company profile that owns the user membership.</param>
    /// <param name="membershipStatus">Current membership state inside the assigned company.</param>
    public User(
        string name,
        string email,
        string passwordHash,
        string role,
        string department,
        string phone,
        string avatarColor,
        bool isActive,
        string lastLogin,
        bool twoFactorEnabled = false,
        int? companyId = null,
        string membershipStatus = "active")
    {
        Name = name;
        Email = email;
        PasswordHash = passwordHash;
        Role = role;
        Department = department;
        Phone = phone;
        AvatarColor = avatarColor;
        IsActive = isActive;
        LastLogin = lastLogin;
        TwoFactorEnabled = twoFactorEnabled;
        CompanyId = companyId;
        MembershipStatus = string.IsNullOrWhiteSpace(membershipStatus) ? "active" : membershipStatus.Trim().ToLowerInvariant();
    }

    /// <summary>
    ///     Creates a user aggregate from the public sign-up command.
    /// </summary>
    /// <param name="command">Sign-up command carrying the registration payload accepted by IAM.</param>
    /// <param name="passwordHash">BCrypt hash generated by the application command service.</param>
    /// <remarks>
    ///     New sign-up accounts start as active because the Sprint 3 backend does not yet include an
    ///     email-verification workflow. The last-login value is initialized as <c>Never</c> to match
    ///     the frontend user list model.
    /// </remarks>
    public User(SignUpCommand command, string passwordHash)
        : this(
            command.Name,
            command.Email,
            passwordHash,
            command.Role,
            command.Department,
            command.Phone,
            command.AvatarColor,
            command.IsActive,
            "Never",
            false,
            command.CompanyId,
            command.MembershipStatus)
    {
    }

    /// <summary>
    ///     Gets the persistence identity generated by the database.
    /// </summary>
    public int Id { get; private set; }

    /// <summary>
    ///     Gets the display name used in authentication responses and user-management listings.
    /// </summary>
    public string Name { get; private set; }

    /// <summary>
    ///     Gets the unique email address used to authenticate the account.
    /// </summary>
    public string Email { get; private set; }

    /// <summary>
    ///     Gets the BCrypt password hash stored for credential verification.
    /// </summary>
    /// <remarks>
    ///     The property is ignored by JSON serialization so REST resources never expose credential
    ///     material even when an aggregate is accidentally returned by a controller.
    /// </remarks>
    [JsonIgnore] public string PasswordHash { get; private set; }

    /// <summary>
    ///     Gets the authorization role displayed and managed by the users frontend module.
    /// </summary>
    public string Role { get; private set; }

    /// <summary>
    ///     Gets the operational department associated with the user.
    /// </summary>
    public string Department { get; private set; }

    /// <summary>
    ///     Gets the optional phone number used as contact metadata.
    /// </summary>
    public string Phone { get; private set; }

    /// <summary>
    ///     Gets the avatar color token consumed by the frontend avatar fallback.
    /// </summary>
    public string AvatarColor { get; private set; }

    /// <summary>
    ///     Gets a value indicating whether the account can sign in.
    /// </summary>
    public bool IsActive { get; private set; }

    /// <summary>
    ///     Gets the last-login display value shown by the current frontend user table.
    /// </summary>
    public string LastLogin { get; private set; }

    /// <summary>
    ///     Gets a value indicating whether the account has two-factor authentication enabled.
    /// </summary>
    /// <remarks>
    ///     Sprint 3 stores the security preference so the frontend Settings screen is backed by the
    ///     IAM context. The actual OTP challenge can be added later without changing this contract.
    /// </remarks>
    public bool TwoFactorEnabled { get; private set; }

    /// <summary>
    ///     Gets the company profile identifier that scopes this account's operational data.
    /// </summary>
    /// <remarks>
    ///     Buildline uses a company-based tenancy model. The value lets the frontend show the right
    ///     company profile and prevents the users module from mixing accounts across companies.
    /// </remarks>
    public int? CompanyId { get; private set; }

    /// <summary>
    ///     Gets the user's membership state inside the assigned company.
    /// </summary>
    /// <remarks>
    ///     Supported values are <c>active</c>, <c>pending</c> and <c>rejected</c>. Pending users can
    ///     authenticate so the frontend can display a waiting-for-approval screen, but they should
    ///     not access operational dashboards until an owner accepts the membership.
    /// </remarks>
    public string MembershipStatus { get; private set; }

    /// <summary>
    ///     Gets or sets the audit timestamp captured when the aggregate is first persisted.
    /// </summary>
    public DateTimeOffset? CreatedAt { get; set; }

    /// <summary>
    ///     Gets or sets the audit timestamp captured when the aggregate is updated.
    /// </summary>
    public DateTimeOffset? UpdatedAt { get; set; }

    /// <summary>
    ///     Updates the last-login display value after a successful authentication flow.
    /// </summary>
    /// <param name="lastLogin">New last-login value formatted by the application layer.</param>
    /// <returns>The same aggregate instance to support fluent domain updates.</returns>
    public User UpdateLastLogin(string lastLogin)
    {
        LastLogin = lastLogin;
        return this;
    }

    /// <summary>
    ///     Updates account metadata managed from the users administration endpoint.
    /// </summary>
    /// <param name="name">Updated display name. If the API received a partial patch, the current value is passed.</param>
    /// <param name="email">Updated unique sign-in email. Uniqueness is validated before this method is called.</param>
    /// <param name="role">Updated application role assigned by an administrator.</param>
    /// <param name="department">Updated department or operational area.</param>
    /// <param name="phone">Updated contact phone value.</param>
    /// <param name="avatarColor">Updated frontend avatar color token.</param>
    /// <param name="isActive">Updated access status used by the sign-in command service.</param>
    /// <param name="twoFactorEnabled">Updated two-factor authentication preference.</param>
    /// <param name="companyId">Updated company profile identifier.</param>
    /// <param name="membershipStatus">Updated company membership state.</param>
    /// <returns>The same aggregate instance with user-management fields replaced.</returns>
    /// <remarks>
    ///     Password and last-login data are intentionally excluded so role/status maintenance cannot
    ///     accidentally reset credentials or authentication history.
    /// </remarks>
    public User UpdateAccountInformation(
        string name,
        string email,
        string role,
        string department,
        string phone,
        string avatarColor,
        bool isActive,
        bool twoFactorEnabled,
        int? companyId,
        string membershipStatus)
    {
        Name = name;
        Email = email;
        Role = role;
        Department = department;
        Phone = phone;
        AvatarColor = avatarColor;
        IsActive = isActive;
        TwoFactorEnabled = twoFactorEnabled;
        CompanyId = companyId;
        MembershipStatus = string.IsNullOrWhiteSpace(membershipStatus) ? MembershipStatus : membershipStatus.Trim().ToLowerInvariant();
        return this;
    }

    /// <summary>
    ///     Replaces the stored password hash after the current password has been verified by the application service.
    /// </summary>
    /// <param name="passwordHash">New BCrypt password hash.</param>
    /// <returns>The same aggregate instance with the credential hash replaced.</returns>
    public User ChangePasswordHash(string passwordHash)
    {
        PasswordHash = passwordHash;
        return this;
    }
}
