using Buildline.Platform.Requisition.Domain.Model.Commands;

namespace Buildline.Platform.Requisition.Domain.Model.Aggregates;

/// <summary>
///     Aggregate root that represents a material in the Buildline construction material references.
/// </summary>
/// <remarks>
///     Materials are shared by requisitions and inventory: requisitions select materials to request,
///     while inventory views inspect current stock, minimum stock and maximum stock by project.
/// </remarks>
public partial class Material
{
    /// <summary>
    ///     Initializes an empty material instance for Entity Framework Core materialization.
    /// </summary>
    /// <remarks>
    ///     Domain code should use public constructors so reference fields are explicitly provided. EF
    ///     Core uses this constructor when rebuilding persisted material aggregates.
    /// </remarks>
    protected Material()
    {
        Sku = string.Empty;
        Name = string.Empty;
        Category = string.Empty;
        Unit = string.Empty;
        Project = string.Empty;
    }

    /// <summary>
    ///     Creates a material aggregate from reference and stock values.
    /// </summary>
    /// <param name="sku">Business SKU used to identify the material in reference views.</param>
    /// <param name="name">Human-readable material name.</param>
    /// <param name="category">Material category name used by filters and reports.</param>
    /// <param name="unit">Measurement unit, such as PCS, Bags, Tons or m3.</param>
    /// <param name="project">Project name associated with the stock record.</param>
    /// <param name="currentStock">Current available stock quantity.</param>
    /// <param name="minStock">Minimum stock threshold used to detect critical stock.</param>
    /// <param name="maxStock">Maximum stock threshold used to guide replenishment planning.</param>
    /// <param name="companyId">Company profile identifier that owns the material reference.</param>
    public Material(
        string sku,
        string name,
        string category,
        string unit,
        string project,
        int currentStock,
        int minStock,
        int maxStock,
        int companyId = 1)
    {
        CompanyId = companyId;
        Sku = sku;
        Name = name;
        Category = category;
        Unit = unit;
        Project = project;
        CurrentStock = currentStock;
        MinStock = minStock;
        MaxStock = maxStock;
    }

    /// <summary>
    ///     Creates a material aggregate from a create-material command.
    /// </summary>
    /// <param name="command">Command carrying reference fields accepted by the application service.</param>
    public Material(CreateMaterialCommand command)
        : this(
            command.Sku,
            command.Name,
            command.Category,
            command.Unit,
            command.Project,
            command.CurrentStock,
            command.MinStock,
            command.MaxStock,
            command.CompanyId)
    {
    }

    /// <summary>
    ///     Gets the persistence identity generated by the database.
    /// </summary>
    public int Id { get; private set; }

    /// <summary>Gets the company profile identifier that owns this operational record.</summary>
    public int CompanyId { get; private set; }

    /// <summary>
    ///     Gets the SKU used by material reference and procurement workflows.
    /// </summary>
    public string Sku { get; private set; }

    /// <summary>
    ///     Gets the material display name.
    /// </summary>
    public string Name { get; private set; }

    /// <summary>
    ///     Gets the material category used for filtering and reporting.
    /// </summary>
    public string Category { get; private set; }

    /// <summary>
    ///     Gets the measurement unit used when requesting or counting this material.
    /// </summary>
    public string Unit { get; private set; }

    /// <summary>
    ///     Gets the project name associated with this material stock record.
    /// </summary>
    public string Project { get; private set; }

    /// <summary>
    ///     Gets the currently available stock quantity.
    /// </summary>
    public int CurrentStock { get; private set; }

    /// <summary>
    ///     Gets the minimum stock threshold.
    /// </summary>
    public int MinStock { get; private set; }

    /// <summary>
    ///     Gets the maximum stock threshold.
    /// </summary>
    public int MaxStock { get; private set; }

    /// <summary>
    ///     Replaces reference and stock information for the material.
    /// </summary>
    /// <param name="sku">Updated SKU value.</param>
    /// <param name="name">Updated material name.</param>
    /// <param name="category">Updated material category.</param>
    /// <param name="unit">Updated measurement unit.</param>
    /// <param name="project">Updated project association.</param>
    /// <param name="currentStock">Updated current stock quantity.</param>
    /// <param name="minStock">Updated minimum stock threshold.</param>
    /// <param name="maxStock">Updated maximum stock threshold.</param>
    /// <remarks>
    ///     Validation remains in the application service so the aggregate focuses on state transition.
    ///     Future inventory rules can be promoted here when stock thresholds become richer invariants.
    /// </remarks>
    public void UpdateReferenceInformation(
        string sku,
        string name,
        string category,
        string unit,
        string project,
        int currentStock,
        int minStock,
        int maxStock)
    {
        Sku = sku;
        Name = name;
        Category = category;
        Unit = unit;
        Project = project;
        CurrentStock = currentStock;
        MinStock = minStock;
        MaxStock = maxStock;
    }
}
