using Buildline.Platform.Shared.Domain.Model.Entities;

namespace Buildline.Platform.Analytics.Domain.Model.Aggregates;

/// <summary>
///     Aggregate root that represents a construction project used as a shared operational reference.
/// </summary>
/// <remarks>
///     Projects are consumed by requisitions, inventory filters, procurement views and analytics.
///     Sprint 3 exposes them as read-only reference data because the current frontend contract needs
///     stable project identifiers and budget metadata before richer project administration exists.
/// </remarks>
public partial class Project : IAuditableEntity
{
    /// <summary>
    ///     Initializes an empty project instance for Entity Framework Core materialization.
    /// </summary>
    /// <remarks>
    ///     Domain code should use the public constructor so required project fields are supplied
    ///     explicitly. EF Core uses this constructor when hydrating records from the database.
    /// </remarks>
    protected Project()
    {
        Name = string.Empty;
        Location = string.Empty;
        Date = string.Empty;
        Status = string.Empty;
    }

    /// <summary>
    ///     Creates a construction project reference with budget and progress metadata.
    /// </summary>
    /// <param name="name">Human-readable project name shown in filters and dashboards.</param>
    /// <param name="location">Geographic location of the construction project.</param>
    /// <param name="budget">Approved project budget used by analytics and budgeting views.</param>
    /// <param name="spent">Current spent amount used to calculate budget health.</param>
    /// <param name="date">Start or reference date formatted as expected by the frontend contract.</param>
    /// <param name="status">Operational status, such as In Progress or At Risk.</param>
    /// <param name="progress">Completion percentage shown by the dashboard.</param>
    /// <param name="companyId">Company profile identifier that owns the project reference.</param>
    public Project(
        string name,
        string location,
        decimal budget,
        decimal spent,
        string date,
        string status,
        int progress,
        int companyId = 1)
    {
        CompanyId = companyId;
        Name = name;
        Location = location;
        Budget = budget;
        Spent = spent;
        Date = date;
        Status = status;
        Progress = progress;
    }

    /// <summary>
    ///     Gets the persistence identity generated by the database.
    /// </summary>
    public int Id { get; private set; }

    /// <summary>Gets the company profile identifier that owns this operational record.</summary>
    public int CompanyId { get; private set; }

    /// <summary>
    ///     Gets the project name displayed by requisition, inventory and budgeting screens.
    /// </summary>
    public string Name { get; private set; }

    /// <summary>
    ///     Gets the city or site location associated with the construction project.
    /// </summary>
    public string Location { get; private set; }

    /// <summary>
    ///     Gets the approved budget amount for the project.
    /// </summary>
    public decimal Budget { get; private set; }

    /// <summary>
    ///     Gets the accumulated spent amount for the project.
    /// </summary>
    public decimal Spent { get; private set; }

    /// <summary>
    ///     Gets the frontend-compatible project date string.
    /// </summary>
    public string Date { get; private set; }

    /// <summary>
    ///     Gets the current project status label.
    /// </summary>
    public string Status { get; private set; }

    /// <summary>
    ///     Gets the project completion percentage from 0 to 100.
    /// </summary>
    public int Progress { get; private set; }

    /// <summary>
    ///     Gets or sets the audit timestamp captured when the project is first persisted.
    /// </summary>
    public DateTimeOffset? CreatedAt { get; set; }

    /// <summary>
    ///     Gets or sets the audit timestamp captured when the project is updated.
    /// </summary>
    public DateTimeOffset? UpdatedAt { get; set; }
}

